blog/urls.py
from django.urls import path

from . import views

app_name = "weblog"
urlpatterns = [
    path(
        "<int:year>/<str:month>/<int:day>/<slug>/",
        views.BlogDateDetailView.as_view(),
        name="entry",
    ),
    path(
        "<int:year>/<str:month>/<int:day>/",
        views.BlogDayArchiveView.as_view(),
        name="archive-day",
    ),
    path(
        "<int:year>/<str:month>/",
        views.BlogMonthArchiveView.as_view(),
        name="archive-month",
    ),
    path("<int:year>/", views.BlogYearArchiveView.as_view(), name="archive-year"),
    path("", views.BlogArchiveIndexView.as_view(), name="index"),
]

fundraising/urls.py
from django.urls import path

from . import views

app_name = "fundraising"
urlpatterns = [
    path("", views.index, name="index"),
    path("donation-session", views.configure_checkout_session, name="donation-session"),
    path("thank-you/", views.thank_you, name="thank-you"),
    path("manage-donations/<hero>/", views.manage_donations, name="manage-donations"),
    path(
        "manage-donations/<hero>/cancel/", views.cancel_donation, name="cancel-donation"
    ),
    path("receive-webhook/", views.receive_webhook, name="receive-webhook"),
    path("update-card/", views.update_card, name="update-card"),
]

fundraising/forms.py
import stripe
from django import forms
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from .models import INTERVAL_CHOICES, LEADERSHIP_LEVEL_AMOUNT, DjangoHero, Donation


class DjangoHeroForm(forms.ModelForm):
    hero_type = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        label=_("I am donating as an"),
        choices=DjangoHero.HERO_TYPE_CHOICES,
        initial=DjangoHero.HERO_TYPE_CHOICES[0][0],
    )
    name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "required",
                "placeholder": _("Your name or the name of your organization"),
            },
        ),
    )
    location = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": (
                    _("Where are you located? (optional; will not be displayed)")
                ),
            },
        ),
    )
    url = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": _("Which URL should we link your name to?"),
            },
        ),
    )
    logo = forms.FileField(
        required=False,
        help_text=_(
            "If you've donated at least US $%d, you can submit your logo and "
            "we will display it, too."
        )
        % LEADERSHIP_LEVEL_AMOUNT,
    )
    is_visible = forms.BooleanField(
        required=False,
        label=_(
            "Yes, display my name, URL, and logo on this site. "
            "It'll be displayed shortly after we verify it."
        ),
    )
    is_subscribed = forms.BooleanField(
        required=False,
        label=_(
            "Yes, the Django Software Foundation can inform me about "
            "future fundraising campaigns by email."
        ),
    )

    class Meta:
        model = DjangoHero
        fields = (
            "hero_type",
            "name",
            "location",
            "url",
            "logo",
            "is_visible",
            "is_subscribed",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.checkbox_fields = []
        self.radio_select_fields = []

        for name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput):
                self.checkbox_fields.append(name)
            elif isinstance(field.widget, forms.RadioSelect):
                self.radio_select_fields.append(name)

    def save(self, commit=True):
        hero = super().save(commit=commit)
        customer = stripe.Customer.retrieve(hero.stripe_customer_id)
        customer.description = hero.name or None
        customer.email = hero.email or None
        customer.save()
        return hero


class StripeTextInput(forms.TextInput):
    """
    Inspired by widgets in django-zebra
    """

    def _add_data_stripe_attr(self, name, kwargs):
        kwargs.setdefault("attrs", {}).update({"data-stripe": name})
        return kwargs

    def _strip_name_attr(self, widget_string, name):
        return widget_string.replace(f'name="{name}"', "")

    def render(self, name, *args, **kwargs):
        kwargs = self._add_data_stripe_attr(name, kwargs)
        rendered = super().render(name, *args, **kwargs)
        return mark_safe(self._strip_name_attr(rendered, name))


class DonateForm(forms.Form):
    """
    Used to generate the HTML form in the fundraising page.
    """

    AMOUNT_CHOICES = (
        (25, _("US $25")),
        (50, _("US $50")),
        (100, _("US $100")),
        (250, _("US $250")),
        (500, _("US $500")),
        (750, _("US $750")),
        (1000, _("US $1,000")),
        (1250, _("US $1,250")),
        (2500, _("US $2,500")),
        ("custom", _("Other amount")),
    )

    amount = forms.ChoiceField(choices=AMOUNT_CHOICES)
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES)
    captcha = ReCaptchaField(widget=ReCaptchaV3(action="form"))


class DonationForm(forms.ModelForm):
    """
    Used in the manage donations view.
    """

    subscription_amount = forms.DecimalField(
        max_digits=9, decimal_places=2, required=True
    )
    # here we're removing "onetime" option from interval choices:
    interval = forms.ChoiceField(choices=INTERVAL_CHOICES[:3], required=True)

    class Meta:
        model = Donation
        fields = ("subscription_amount", "interval")

    def save(self, commit=True, *args, **kwargs):
        donation = super().save(commit=commit)
        interval = self.cleaned_data.get("interval")
        amount = self.cleaned_data.get("subscription_amount")

        # Send data to Stripe
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        # TODO: Setting the plan is deprecated — use Price API instead.
        subscription.plan = interval
        subscription.quantity = int(amount)

        subscription.save()

        return donation


class PaymentForm(forms.Form):
    """
    Used to validate values when configuring the Stripe Session.

    `amount` can be any integer, so a ChoiceField is not appropriate.
    """

    # NOTE: `action` needs to match the one used in stripe-donation.js
    captcha = ReCaptchaField(widget=ReCaptchaV3(action="form"))
    amount = forms.IntegerField(
        required=True,
        min_value=1,  # Minimum payment from Stripe API
        max_value=999_999,  # Reject clearly unrealistic amounts.
    )
    interval = forms.ChoiceField(
        required=True,
        choices=INTERVAL_CHOICES,
    )

fundraising/views.py
import decimal
import logging

import stripe
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.forms.models import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .forms import DjangoHeroForm, DonationForm, PaymentForm
from .models import DjangoHero, Donation, Payment, Testimonial

logger = logging.getLogger(__name__)


def index(request):
    testimonial = Testimonial.objects.filter(is_active=True).order_by("?").first()
    return render(
        request,
        "fundraising/index.html",
        {
            "testimonial": testimonial,
        },
    )


@require_POST
def configure_checkout_session(request):
    """
    Configure the payment session for Stripe.
    Return the Session ID.

    Key attributes are:

    - mode: payment (for one-time charge) or subscription
    - line_items: including price_data because users configure the donation
                  price.

    TODOs

    - Standard amounts could use active Prices, rather than ad-hoc price_data.
    - Tie Stripe customers to site User accounts.
      - If a user is logged in, we can create the session for the correct
        customer.
      - Stripe's documented flows are VERY keen that we create the customer
        first, although the session will do that if we don't.
    - Allow selecting currency. (Smaller task.) Users receive an additional
      charge making payments in foreign currencies. Stripe will convert all
      payments without further charge.
    """

    # Form data:
    # - The interval: which determines the Product and the mode.
    # - The amount: which goes to the Price data.
    form = PaymentForm(request.POST)
    if not form.is_valid():
        data = {"success": False, "error": form.errors}
        return JsonResponse(data)

    amount = form.cleaned_data["amount"]
    interval = form.cleaned_data["interval"]

    product_details = settings.PRODUCTS[interval]
    is_subscription = product_details.get("recurring", True)

    price_data = {
        "currency": "usd",
        "unit_amount": amount * 100,
        "product": product_details["product_id"],
    }
    if is_subscription:
        price_data["recurring"] = {
            "interval": product_details["interval"],
            "interval_count": product_details["interval_count"],
        }

    try:
        session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[{"price_data": price_data, "quantity": 1}],
            mode="subscription" if is_subscription else "payment",
            success_url=request.build_absolute_uri(reverse("fundraising:thank-you")),
            cancel_url=request.build_absolute_uri(reverse("fundraising:index")),
            # TODO: Drop this when updating API.
            stripe_version="2020-08-27",
        )

        return JsonResponse({"success": True, "sessionId": session["id"]})
    except Exception as e:
        logger.exception("Error configuring Stripe session.")
        return JsonResponse({"success": False, "error": str(e)})


def thank_you(request):
    """
    Generic thank you page. In theory only reached via successful payment, but
    no information is passed from Stripe to be sure.
    """
    return render(request, "fundraising/thank-you.html", {})


# TODO: Use Stripe's customer portal.
@never_cache
def manage_donations(request, hero):
    hero = get_object_or_404(DjangoHero, pk=hero)
    recurring_donations = hero.donation_set.exclude(stripe_subscription_id="")
    past_payments = (
        Payment.objects.filter(donation__donor=hero)
        .select_related("donation")
        .order_by("-date")
    )

    ModifyDonationsFormset = modelformset_factory(Donation, form=DonationForm, extra=0)

    if request.method == "POST":
        hero_form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=hero,
        )
        modify_donations_formset = ModifyDonationsFormset(
            request.POST, queryset=recurring_donations
        )

        if hero_form.is_valid() and modify_donations_formset.is_valid():
            hero_form.save()
            modify_donations_formset.save()
            messages.success(request, _("Your information has been updated."))
    else:
        hero_form = DjangoHeroForm(instance=hero)
        modify_donations_formset = ModifyDonationsFormset(queryset=recurring_donations)

    return render(
        request,
        "fundraising/manage-donations.html",
        {
            "hero": hero,
            "hero_form": hero_form,
            "modify_donations_formset": modify_donations_formset,
            "recurring_donations": recurring_donations,
            "past_payments": past_payments,
            "stripe_publishable_key": settings.STRIPE_PUBLISHABLE_KEY,
        },
    )


@require_POST
def update_card(request):
    donation = get_object_or_404(Donation, id=request.POST["donation_id"])
    try:
        stripe.Customer.modify(
            donation.stripe_customer_id,
            source=request.POST["stripe_token"],
        )
    except stripe.error.StripeError as e:
        data = {"success": False, "error": str(e)}
    else:
        data = {"success": True}
    return JsonResponse(data)


@require_POST
def cancel_donation(request, hero):
    donation_id = request.POST.get("donation")
    hero = get_object_or_404(DjangoHero, pk=hero)
    donations = hero.donation_set.exclude(stripe_subscription_id="")
    donation = get_object_or_404(donations, pk=donation_id)

    customer = stripe.Customer.retrieve(
        donation.stripe_customer_id, expand=["subscriptions"]
    )
    customer.subscriptions.retrieve(donation.stripe_subscription_id).delete()

    donation.stripe_subscription_id = ""
    donation.save()

    messages.success(request, _("Your donation has been canceled."))
    return redirect("fundraising:manage-donations", hero=hero.pk)


@require_POST
@csrf_exempt
def receive_webhook(request):
    try:
        event = stripe.Webhook.construct_event(
            request.body,
            request.headers["stripe-signature"],
            settings.STRIPE_ENDPOINT_SECRET,
        )
    except (KeyError, ValueError, stripe.error.SignatureVerificationError):
        return HttpResponse(status=422)

    return WebhookHandler(event).handle()


class WebhookHandler:
    def __init__(self, event):
        self.event = event

    def handle(self):
        handlers = {
            "invoice.payment_succeeded": self.payment_succeeded,
            "invoice.payment_failed": self.payment_failed,
            "customer.subscription.deleted": self.subscription_cancelled,
            "checkout.session.completed": self.checkout_session_completed,
        }
        handler = handlers.get(self.event.type, lambda: HttpResponse(status=422))
        if not self.event.data.object:
            return HttpResponse(status=422)
        return handler()

    def payment_succeeded(self):
        invoice = self.event.data.object
        # Ensure we haven't already processed this payment
        if Payment.objects.filter(stripe_charge_id=invoice.charge).exists():
            # We need a 2xx response otherwise Stripe will keep trying.
            return HttpResponse()
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription
        )
        amount = decimal.Decimal(invoice.total) / 100
        if invoice.charge:
            donation.payment_set.create(amount=amount, stripe_charge_id=invoice.charge)
        return HttpResponse(status=201)

    def subscription_cancelled(self):
        subscription = self.event.data.object
        donation = get_object_or_404(Donation, stripe_subscription_id=subscription.id)
        donation.stripe_subscription_id = ""
        donation.save()

        mail_text = render_to_string(
            "fundraising/email/subscription_cancelled.txt", {"donation": donation}
        )
        send_mail(
            _("Payment cancelled"),
            mail_text,
            settings.DEFAULT_FROM_EMAIL,
            [donation.donor.email],
        )

        return HttpResponse(status=204)

    def payment_failed(self):
        invoice = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription
        )

        mail_text = render_to_string(
            "fundraising/email/payment_failed.txt", {"donation": donation}
        )
        send_mail(
            _("Payment failed"),
            mail_text,
            settings.DEFAULT_FROM_EMAIL,
            [donation.donor.email],
        )

        return HttpResponse(status=204)

    def get_donation_interval(self, session):
        """
        Helper to determine Donation.interval from completed Stripe Session.
        """
        if session.mode == "payment":
            return "onetime"

        # Access the interval via the attached price object.
        # See https://stripe.com/docs/api/subscriptions/object
        # TODO: remove stripe_version when updating account settings.
        subscription = stripe.Subscription.retrieve(
            session.subscription, stripe_version="2020-08-27"
        )
        recurrance = subscription["items"].data[0].price.recurring
        if recurrance.interval == "year":
            return "yearly"
        elif recurrance.interval_count == 3:
            return "quarterly"
        else:
            return "monthly"

    def checkout_session_completed(self):
        """
        > Occurs when a Checkout Session has been successfully completed.

djangoproject/templates/fundraising/manage-donations.html
{% extends 'fundraising/index.html' %}
{% load i18n static %}

{% block messages %}

  {% if messages %}
    {% for message in messages %}
      <p>{{ message }}</p>
    {% endfor %}
    <hr>
  {% endif %}

{% endblock %}

{% block content %}

  <h1>{% translate "Manage your donations to the Django Software Foundation" %}</h1>
  <p>
    {% blocktranslate trimmed %}
      Your support is <strong>invaluable</strong> to continue the rapid development
      of Django and helps the <strong>Django Fellowship</strong> program in particular.
      Thank you!
    {% endblocktranslate %}
  </p>

  <form enctype="multipart/form-data" action="" method="post" class="form-input django-hero-form"
        data-stripe-key="{{ stripe_publishable_key }}" data-stripe-icon="{% static 'img/dj-stripe-icon.jpg' %}"
        data-update-card-url="{% url 'fundraising:update-card' %}">
    <h2>{% translate "Manage your participation in the fundraising campaigns" %}</h2>
    <p>{% translate "Information entered below will be visible on all of your donations to the Django Project." %}</p>
    {% csrf_token %}
    {% include 'fundraising/includes/_form.html' with form=hero_form %}
    <p class="submit">
      <input type="submit" class="cta" value="{% translate "Save &rarr;" context "Save personal details about donation" %}">
    </p>
  {# Always include to avoid "Management form has been tampered with" if no recurring donations exist #}
    {{ modify_donations_formset.management_form }}
    {% if recurring_donations %}
      <hr />
      <h2>{% translate "Modify your recurring donations" %}</h2>
      <p>{% translate "Update the time interval or amount of your recurring donation here:" %}</p>
      {% for form in modify_donations_formset %}
        {% include 'fundraising/includes/_form.html' %}
        <div class="change-card-container">
          <input type="button" value="Change card details" class="change-card cta outline inline"
                 data-donation-id="{{ form.instance.id }}" data-donor-email="{{ hero.email }}">
          <span class="change-card-result"></span>
        </div>
      {% endfor %}
      <p class="submit">
        <input type="submit" class="cta" value="{% translate "Save &rarr;" context "Save personal details about donation" %}">
      </p>
      </form>
      <hr />
      <h2>{% translate "Cancel your recurring donations" %}</h2>
      <p>{% translate "You can cancel your recurring donation to the Django Software Foundation anytime." %}</p>
      <ul>
        {% for donation in recurring_donations %}
          <li>
            {% blocktranslate trimmed with interval=donation.interval amount=donation.subscription_amount %}
              Your {{ interval }} recurring donation of ${{ amount }}.
            {% endblocktranslate %}
            <form method="POST" action="{% url 'fundraising:cancel-donation' hero.pk %}">
              {% csrf_token %}
              <input name="donation" type="hidden" value="{{ donation.pk }}">
              <input type="submit" value="{% translate "cancel this donation" %}">
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      </form>
    {% endif %}
    {% if past_payments %}
      <hr />
      <h2>{% translate "Your past donations" %}</h2>
      <ul>
        {% for payment in past_payments %}
          <li>
            ${{ payment.amount }} on {{ payment.date|date:"DATETIME_FORMAT" }}
            ({{ payment.donation.get_interval_display }})
          </li>
        {% endfor %}
      </ul>
    {% endif %}
{% endblock %}

{% block content-extra %}{% endblock %}

djangoproject/templates/fundraising/thank-you.html
{% extends 'fundraising/index.html' %}
{% load humanize i18n static %}

{% block content %}
  <h1>{% translate "Thank you for supporting the Django Project!" %}</h1>
  <p>
    {% blocktranslate trimmed %}
      Your support is <strong>invaluable</strong> to continue the rapid development
      of Django and helps the <strong>Django Fellowship</strong> program in particular.
    {% endblocktranslate %}
  </p>

  <p>
    {% blocktranslate trimmed %}
      Please help us spread the word and encourage your friends and colleagues to
      donate. Thank you!
    {% endblocktranslate %}
  </p>

  <a href="https://twitter.com/intent/tweet?button_hashtag=SupportDjango&text=I+just+donated+to+support+the+Django+Software+Foundation.+Join+me!+https%3A%2F%2Fwww.djangoproject.com%2Ffundraising%2F"
     class="twitter-hashtag-button" data-related="djangoproject">Tweet #SupportDjango</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

  <p>
    {% blocktranslate trimmed %}
      You should receive an email shortly, with confirmation of your donation,
      details of badges you can display to show you support of Django, managing your
      donation,  and how you can have your name or company displayed on the
      Fundraising page and in the sidebar on the Django Project website.
    {% endblocktranslate %}
  </p>

  <p>{% translate "Welcome aboard! ⛵️" %}</p>

  <hr>

  <p>
    {% blocktranslate trimmed %}
      If you have any <strong>problems</strong> with your donation please email
      <a href="mailto:donations@djangoproject.com">donations@djangoproject.com</a> for help.
    {% endblocktranslate %}
  </p>

{% endblock %}

{% block content-extra %}{% endblock %}