blog/urls.py
from django.urls import path

from . import views

app_name = "weblog"
urlpatterns = [
    path(
        "<int:year>/<str:month>/<int:day>/<slug>/",
        views.BlogDateDetailView.as_view(),
        name="entry",
    ),
    path(
        "<int:year>/<str:month>/<int:day>/",
        views.BlogDayArchiveView.as_view(),
        name="archive-day",
    ),
    path(
        "<int:year>/<str:month>/",
        views.BlogMonthArchiveView.as_view(),
        name="archive-month",
    ),
    path("<int:year>/", views.BlogYearArchiveView.as_view(), name="archive-year"),
    path("", views.BlogArchiveIndexView.as_view(), name="index"),
]

fundraising/urls.py
from django.urls import path

from . import views

app_name = "fundraising"
urlpatterns = [
    path("", views.index, name="index"),
    path("donation-session", views.configure_checkout_session, name="donation-session"),
    path("thank-you/", views.thank_you, name="thank-you"),
    path("manage-donations/<hero>/", views.manage_donations, name="manage-donations"),
    path(
        "manage-donations/<hero>/cancel/", views.cancel_donation, name="cancel-donation"
    ),
    path("receive-webhook/", views.receive_webhook, name="receive-webhook"),
    path("update-card/", views.update_card, name="update-card"),
]

djangoproject/templates/includes/footer.html
<footer>
  <div class="subfooter">
    <div class="container">
      <h2 class="visuallyhidden">Django Links</h2>
      <div class="column-container">
        <div class="col-learn-more">
          <h3>Learn More</h3>
          <ul>
            <li><a href="{% url 'overview' %}">About Django</a></li>
            {% comment %}<li><a href="{% url 'case_study_index' %}">Case Studies</a></li>{% endcomment %}
            <li><a href="{% url 'start' %}">Getting Started with Django</a></li>
            <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/organization" host 'docs' %}">Team
              Organization</a></li>
            <li><a href="{% url 'homepage' %}foundation/">Django Software Foundation</a></li>
            <li><a href="{% url 'code_of_conduct' %}">Code of Conduct</a></li>
            <li><a href="{% url 'diversity' %}">Diversity Statement</a></li>
          </ul>
        </div>

        <div class="col-get-involved">
          <h3>Get Involved</h3>
          <ul>
            <li><a href="{% url 'community-index' %}">Join a Group</a></li>
            <li><a href="{% url 'document-detail' lang='en' version='dev' url="internals/contributing" host 'docs' %}">Contribute
              to Django</a></li>
            <li><a
              href="{% url 'document-detail' lang='en' version='dev' url="internals/contributing/bugs-and-features" host 'docs' %}">Submit
              a Bug</a></li>
            <li><a
              href="{% url 'document-detail' lang='en' version='dev' url="internals/security" host 'docs' %}#reporting-security-issues">Report
              a Security Issue</a></li>
            <li><a href="{% url 'members:individual-members' %}">Individual membership</a></li>
          </ul>
        </div>

        <div class="col-get-help">
          <h3>Get Help</h3>
          <ul>
            <li><a href="{% url 'document-detail' lang='en' version='stable' url='faq' host 'docs' %}">Getting Help FAQ</a>
            </li>
            <li><a href="https://chat.djangoproject.com" target="_blank">Django Discord</a></li>
            <li><a href="https://forum.djangoproject.com/" target="_blank">Official Django Forum</a></li>
          </ul>
        </div>

        <div class="col-follow-us">
          <h3>Follow Us</h3>
          <ul>
            <li><a href="https://github.com/django">GitHub</a></li>
            <li><a href="https://twitter.com/djangoproject">Twitter</a></li>
            <li><a href="https://fosstodon.org/@django" rel="me">Fediverse (Mastodon)</a></li>
            <li><a href="{% url 'weblog-feed' %}">News RSS</a></li>
          </ul>
        </div>

        <div class="col-support-us">
          <h3>Support Us</h3>
          <ul>
            <li><a href="{% url "fundraising:index" %}">Sponsor Django</a></li>
            <li><a href="/foundation/corporate-membership/">Corporate membership</a></li>
            <li><a href="https://django.threadless.com/" target="_blank">Official merchandise store</a></li>
            <li><a href="/foundation/donate/#benevity-giving">Benevity Workplace Giving Program</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="footer">
    <div class="container">
      <div class="footer-logo">
        <a class="logo" href="{% url 'homepage' %}">Django</a>
      </div>
      <ul class="thanks">
        <li>
          <span>Hosting by</span> <a class="in-kind-donors" href="{% url 'fundraising:index' %}#in-kind-donors">In-kind
            donors</a>
        </li>
        <li class="design"><span>Design by</span> <a class="threespot" href="https://www.threespot.com">Threespot</a>
          <span class="ampersand">&amp;</span> <a class="andrevv" href="http://andrevv.com/">andrevv</a></li>
      </ul>
      <p class="copyright">&copy; 2005-{% now "Y" %}
        <a href="{% url 'homepage' %}foundation/"> Django Software
          Foundation</a> and individual contributors. Django is a
        <a href="{% url 'homepage' %}trademarks/">registered
          trademark</a> of the Django Software Foundation.
      </p>
    </div>
  </div>

</footer>

djangoproject/templates/includes/header.html
<header id="top">
  <div class="container container--flex--wrap--mobile">
    <a class="logo" href="{% url 'homepage' %}">Django</a>
    <p class="meta">The web framework for perfectionists with deadlines.</p>
    <div class="mobile-toggle">
      {% include "includes/toggle_theme.html" %}
    </div>
    <button class="menu-button">
      <i class="icon icon-reorder"></i>
      <span class="visuallyhidden">Menu</span>
    </button>
    <nav aria-labelledby="navigation-header">
      <span id="navigation-header" class="visuallyhidden">Main navigation</span>
      <ul>
        <li{% if 'start' in request.path %} class="active"{% endif %}>
          <a href="{% url 'overview' %}">Overview</a>
        </li>
        <li{% if 'download' in request.path %} class="active"{% endif %}>
          <a href="{% url 'download' %}">Download</a>
        </li>
        <li{% if request.host.name == 'docs' %} class="active"{% endif %}>
          <a href="{% block doc_url %}{% url 'homepage' host 'docs' %}{% endblock %}">Documentation</a>
        </li>
        <li{% if 'weblog' in request.path %} class="active"{% endif %}>
          <a href="{% url 'weblog:index' %}">News</a>
        </li>
        <li{% if 'community' in request.path or 'conduct' in request.path %} class="active"{% endif %}>
          <a href="{% url 'community-index' %}">Community</a>
        </li>
        <li>
          <a href="https://github.com/django/django" target="_blank" rel="noopener">Code</a>
        </li>
        <li>
          <a href="https://code.djangoproject.com/">Issues</a>
        </li>
        <li{% if 'foundation' in request.path %} class="active"{% endif %}>
          <a href="{% url 'homepage' %}foundation/">About</a>
        </li>
        <li{% if 'fundraising' in request.path %} class="active"{% endif %}>
          <a href="{% url 'fundraising:index' %}">&#9829; Donate</a>
        </li>
        <li>
          {% include "includes/toggle_theme.html" %}
        </li>
      </ul>
    </nav>
  </div>
</header>

djangoproject/templates/includes/toggle_theme.html
{% load i18n %}

<button class="theme-toggle">
  <div class="visually-hidden theme-label-when-auto">{% translate 'Toggle theme (current theme: auto)' %}</div>
  <div class="visually-hidden theme-label-when-light">{% translate 'Toggle theme (current theme: light)' %}</div>
  <div class="visually-hidden theme-label-when-dark">{% translate 'Toggle theme (current theme: dark)' %}</div>

  <div class="visually-hidden">Toggle Light / Dark / Auto color theme</div>
  <svg aria-hidden="true" class="theme-icon-when-auto">
    <use xlink:href="#icon-auto" />
  </svg>
  <svg aria-hidden="true" class="theme-icon-when-dark">
    <use xlink:href="#icon-moon" />
  </svg>
  <svg aria-hidden="true" class="theme-icon-when-light">
    <use xlink:href="#icon-sun" />
  </svg>
</button>